#!/usr/bin/env python3
"""Render GitHub label taxonomy artifacts from one checked-in manifest."""

from __future__ import annotations

import argparse
import functools
import json
import re
import sys
from pathlib import Path
from textwrap import dedent, indent


GENERATED_HEADER = "# Generated by scripts/sync_github_labels.py. Do not edit manually.\n\n"
MARKDOWN_GENERATED_HEADER = "<!-- Generated by scripts/sync_github_labels.py. Do not edit manually. -->\n\n"


def load_taxonomy(repo_root: Path) -> dict:
    taxonomy_path = repo_root / ".github" / "label_taxonomy.json"
    return json.loads(taxonomy_path.read_text())


def label_entries(taxonomy: dict) -> list[dict]:
    labels: list[dict] = []
    for key in ("surfaces", "domains", "general_labels", "size_labels"):
        labels.extend(taxonomy[key])
    return labels


def path_labeled_entries(taxonomy: dict) -> list[dict]:
    entries: list[dict] = []
    for key in ("surfaces", "general_labels"):
        for entry in taxonomy[key]:
            if entry.get("paths"):
                entries.append(entry)
    return entries


def normalize_repo_path(repo_path: str) -> str:
    normalized_path = repo_path.replace("\\", "/")
    while normalized_path.startswith("./"):
        normalized_path = normalized_path[2:]
    return normalized_path


def validate_supported_glob_pattern(pattern: str) -> str:
    normalized_pattern = normalize_repo_path(pattern)

    if not normalized_pattern:
        raise ValueError("empty patterns are not supported")

    if "//" in normalized_pattern:
        raise ValueError("empty path segments are not supported")

    unsupported_characters = "[]{}!+@()"
    found_unsupported_characters: list[str] = []
    for character in unsupported_characters:
        if character not in normalized_pattern:
            continue
        found_unsupported_characters.append(character)

    if found_unsupported_characters:
        unsupported_summary = " ".join(found_unsupported_characters)
        raise ValueError(
            "unsupported glob tokens found; "
            "semantic matcher only supports literals, *, ?, and ** path segments "
            f"({unsupported_summary})"
        )

    segments = normalized_pattern.split("/")
    for segment in segments:
        if segment:
            has_double_star = "**" in segment
            is_double_star_segment = segment == "**"
            if has_double_star and not is_double_star_segment:
                raise ValueError(
                    "semantic matcher only supports ** as a full path segment "
                    f"(pattern: {normalized_pattern})"
                )
            continue

        raise ValueError("empty path segments are not supported")

    return normalized_pattern


def glob_segment_to_regex(segment: str) -> str:
    regex_parts: list[str] = []
    for character in segment:
        if character == "*":
            regex_parts.append("[^/]*")
            continue
        if character == "?":
            regex_parts.append("[^/]")
            continue
        regex_parts.append(re.escape(character))
    return "".join(regex_parts)


def glob_pattern_to_regex(pattern: str) -> str:
    # The managed taxonomy uses a small glob subset, so the matcher stays deliberately narrow.
    normalized_pattern = validate_supported_glob_pattern(pattern)
    segments = normalized_pattern.split("/")
    regex_parts: list[str] = ["^"]
    segment_count = len(segments)

    for index, segment in enumerate(segments):
        is_last_segment = index == segment_count - 1

        if segment == "**":
            if is_last_segment:
                regex_parts.append(".*")
            else:
                regex_parts.append("(?:[^/]+/)*")
            continue

        segment_regex = glob_segment_to_regex(segment)
        regex_parts.append(segment_regex)

        if not is_last_segment:
            regex_parts.append("/")

    regex_parts.append("$")
    return "".join(regex_parts)


@functools.lru_cache(maxsize=None)
def compile_glob_pattern(pattern: str) -> re.Pattern[str]:
    regex_text = glob_pattern_to_regex(pattern)
    return re.compile(regex_text)


def path_matches_pattern(repo_path: str, pattern: str) -> bool:
    normalized_path = normalize_repo_path(repo_path)
    compiled_pattern = compile_glob_pattern(pattern)
    return compiled_pattern.match(normalized_path) is not None


def labels_for_path(taxonomy: dict, repo_path: str) -> list[str]:
    matching_labels: list[str] = []
    entries = path_labeled_entries(taxonomy)
    for entry in entries:
        patterns = entry["paths"]
        for pattern in patterns:
            does_match = path_matches_pattern(repo_path, pattern)
            if not does_match:
                continue
            matching_labels.append(entry["name"])
            break
    matching_labels.sort()
    return matching_labels


def check_semantic_matcher_support(taxonomy: dict) -> list[str]:
    failures: list[str] = []
    entries = path_labeled_entries(taxonomy)

    for entry in entries:
        label_name = entry["name"]
        patterns = entry["paths"]

        for pattern in patterns:
            try:
                compile_glob_pattern(pattern)
            except ValueError as error:
                failure_message = (
                    f"unsupported semantic matcher pattern for {label_name}: "
                    f"{pattern} ({error})"
                )
                failures.append(failure_message)

    return failures


def semantic_regression_cases() -> list[dict]:
    # These representative paths lock the intended routing semantics without duplicating the full repo tree.
    cases: list[dict] = []

    cases.append(
        {
            "path": "README.md",
            "labels": ["docs", "documentation"],
        }
    )
    cases.append(
        {
            "path": "docs/references/github-collaboration.md",
            "labels": ["docs", "documentation"],
        }
    )
    cases.append(
        {
            "path": "docs/design-docs/provider-runtime-roadmap.md",
            "labels": ["documentation", "spec"],
        }
    )
    cases.append(
        {
            "path": "docs/releases/v0.1.0-alpha.2.md",
            "labels": ["documentation"],
        }
    )
    cases.append(
        {
            "path": ".github/workflows/labeler.yml",
            "labels": ["ci", "github_actions"],
        }
    )
    cases.append(
        {
            "path": "Cargo.toml",
            "labels": ["dependencies"],
        }
    )
    cases.append(
        {
            "path": "crates/app/Cargo.toml",
            "labels": ["dependencies"],
        }
    )

    return cases


def check_semantic_regression_cases(taxonomy: dict) -> list[str]:
    failures = check_semantic_matcher_support(taxonomy)
    cases = semantic_regression_cases()

    for case in cases:
        case_path = case["path"]
        expected_labels = sorted(case["labels"])
        actual_labels = labels_for_path(taxonomy, case_path)

        if actual_labels == expected_labels:
            continue

        failure_message = (
            f"semantic label mismatch for {case_path}: "
            f"expected {expected_labels}, got {actual_labels}"
        )
        failures.append(failure_message)

    return failures


def render_labeler(taxonomy: dict) -> str:
    blocks: list[str] = [GENERATED_HEADER.rstrip()]
    for entry in path_labeled_entries(taxonomy):
        lines = [f'"{entry["name"]}":', "  - changed-files:", "      - any-glob-to-any-file:"]
        for path in entry["paths"]:
            lines.append(f'          - "{path}"')
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks) + "\n"


def render_workflow(taxonomy: dict) -> str:
    # This renderer nests Python f-strings, GitHub expressions, and JS template
    # literals, so brace-heavy sections intentionally use doubled braces.
    managed_labels = [
        {
            "name": entry["name"],
            "color": entry["color"],
            "description": entry["description"],
        }
        for entry in label_entries(taxonomy)
    ]
    surface_label_map = {
        entry["option"]: entry["name"] for entry in taxonomy["surfaces"]
    }
    surface_label_map["Unknown / needs triage"] = None
    legacy_labels_literal = indent(
        json.dumps(taxonomy["legacy_labels"], indent=2, ensure_ascii=False),
        " " * 12,
    ).lstrip()

    managed_labels_literal = indent(
        json.dumps(managed_labels, indent=2, ensure_ascii=False),
        " " * 12,
    ).lstrip()
    surface_map_literal = indent(
        json.dumps(surface_label_map, indent=2, ensure_ascii=False),
        " " * 12,
    ).lstrip()

    script_sync = dedent(
        f"""\
        const managedLabels = {managed_labels_literal};
        const legacyLabels = {legacy_labels_literal};

        async function getLabelOrNull(name) {{
          try {{
            const {{ data }} = await github.rest.issues.getLabel({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              name
            }});
            return data;
          }} catch (error) {{
            if (error.status === 404) {{
              return null;
            }}
            throw error;
          }}
        }}

        for (const legacy of legacyLabels) {{
          const legacyLabel = await getLabelOrNull(legacy.name);
          if (!legacyLabel) {{
            continue;
          }}

          if (!legacy.replacement) {{
            await github.rest.issues.deleteLabel({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: legacy.name
            }});
            core.info(`Deleted legacy label ${{legacy.name}}`);
            continue;
          }}

          const replacement = managedLabels.find((label) => label.name === legacy.replacement);
          if (!replacement) {{
            throw new Error(`Missing managed replacement for legacy label ${{legacy.name}}`);
          }}

          const replacementLabel = await getLabelOrNull(replacement.name);
          if (!replacementLabel) {{
            await github.rest.issues.updateLabel({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: legacy.name,
              new_name: replacement.name,
              color: replacement.color,
              description: replacement.description
            }});
            core.info(`Renamed legacy label ${{legacy.name}} to ${{replacement.name}}`);
            continue;
          }}

          let page = 1;
          while (true) {{
            const {{ data: issues }} = await github.rest.issues.listForRepo({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "all",
              labels: legacy.name,
              per_page: 100,
              page
            }});

            if (issues.length === 0) {{
              break;
            }}

            for (const issue of issues) {{
              const labelNames = issue.labels
                .map((label) => typeof label === "string" ? label : label.name)
                .filter(Boolean);
              const mergedLabels = labelNames.filter((name) => name !== legacy.name);
              if (!mergedLabels.includes(replacement.name)) {{
                mergedLabels.push(replacement.name);
              }}

              await github.rest.issues.setLabels({{
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: mergedLabels
              }});
            }}

            if (issues.length < 100) {{
              break;
            }}

            page += 1;
          }}

          await github.rest.issues.deleteLabel({{
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: legacy.name
          }});
          core.info(`Migrated legacy label ${{legacy.name}} to ${{replacement.name}}`);
        }}

        for (const label of managedLabels) {{
          try {{
            const {{ data: current }} = await github.rest.issues.getLabel({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name
            }});

            const currentDescription = current.description || "";
            if (
              current.color.toLowerCase() !== label.color.toLowerCase() ||
              currentDescription !== label.description
            ) {{
              await github.rest.issues.updateLabel({{
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                new_name: label.name,
                color: label.color,
                description: label.description
              }});
              core.info(`Updated label ${{label.name}}`);
            }}
          }} catch (error) {{
            if (error.status !== 404) {{
              throw error;
            }}

            await github.rest.issues.createLabel({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: label.name,
              color: label.color,
              description: label.description
            }});
            core.info(`Created label ${{label.name}}`);
          }}
        }}

        core.notice(`Managed ${{managedLabels.length}} labels.`);
        """
    ).rstrip()

    script_issue = dedent(
        f"""\
        const issue = context.payload.issue;
        const surfaceLabelMap = {surface_map_literal};

        const managedSurfaceLabels = Object.values(surfaceLabelMap).filter(Boolean);
        const body = (issue.body || "").replace(/\\r\\n/g, "\\n");
        const match = body.match(/^### Surface\\s*\\n+([^\\n]+)/m);
        const selectedSurface = match ? match[1].trim() : null;
        const nextSurfaceLabel = selectedSurface ? surfaceLabelMap[selectedSurface] : null;

        const {{ data: existingLabels }} = await github.rest.issues.listLabelsOnIssue({{
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: issue.number
        }});

        const mergedLabels = existingLabels
          .map((label) => label.name)
          .filter((name) => !managedSurfaceLabels.includes(name));

        if (nextSurfaceLabel) {{
          mergedLabels.push(nextSurfaceLabel);
        }}

        await github.rest.issues.setLabels({{
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: issue.number,
          labels: mergedLabels
        }});

        if (selectedSurface) {{
          core.notice(`Resolved issue surface "${{selectedSurface}}" to ${{nextSurfaceLabel ?? "no managed surface label"}}.`);
        }} else {{
          core.notice("No Surface section found in issue body; left managed surface labels cleared.");
        }}
        """
    ).rstrip()

    content = f"""\
{GENERATED_HEADER}name: labeler

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited
  issues:
    types:
      - opened
      - edited
      - reopened
  workflow_dispatch:

concurrency:
  group: labeler-${{{{ github.event.pull_request.number || github.event.issue.number || github.run_id }}}}
  cancel-in-progress: true

jobs:
  sync-managed-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Ensure managed labels exist
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
{indent(script_sync, " " * 12)}

  label-pull-request:
    if: ${{{{ github.event_name == 'pull_request_target' }}}}
    needs: sync-managed-labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout base repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Apply path labels
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: ${{{{ secrets.GITHUB_TOKEN }}}}
          configuration-path: .github/labeler.yml
          sync-labels: true

      - name: Apply size label
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
            const issueNumber = context.payload.pull_request.number;
            const sizeLabels = ["size: XS", "size: S", "size: M", "size: L", "size: XL"];
            const files = await github.paginate(github.rest.pulls.listFiles, {{
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: issueNumber,
              per_page: 100
            }});

            const changedLines = files.reduce((total, file) => total + file.additions + file.deletions, 0);

            let sizeLabel = "size: XL";
            if (changedLines <= 50) {{
              sizeLabel = "size: XS";
            }} else if (changedLines <= 200) {{
              sizeLabel = "size: S";
            }} else if (changedLines <= 500) {{
              sizeLabel = "size: M";
            }} else if (changedLines <= 1000) {{
              sizeLabel = "size: L";
            }}

            const {{ data: existingLabels }} = await github.rest.issues.listLabelsOnIssue({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            }});

            const mergedLabels = [
              ...existingLabels
                .map((label) => label.name)
                .filter((name) => !sizeLabels.includes(name)),
              sizeLabel
            ];

            await github.rest.issues.setLabels({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: mergedLabels
            }});

            core.notice(`Applied ${{sizeLabel}} from ${{changedLines}} changed lines.`);

  label-issue-surface:
    if: ${{{{ github.event_name == 'issues' }}}}
    needs: sync-managed-labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Sync issue surface label from form
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          script: |
{indent(script_issue, " " * 12)}
"""
    return content


def render_surface_options(taxonomy: dict) -> str:
    lines = [f"        - {entry['option']}" for entry in taxonomy["surfaces"]]
    lines.append("        - Unknown / needs triage")
    return "\n".join(lines)


def render_bug_template(taxonomy: dict) -> str:
    options = render_surface_options(taxonomy)
    return f"""\
{GENERATED_HEADER}name: Bug Report
description: Report a reproducible defect in LoongClaw's active `dev` branch or latest stable release.
title: "[Bug]: "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report.
        Please keep the report evidence-based, redact secrets, and provide the shortest reproducible path you can.
        If you are still figuring out whether this is a bug or a setup problem, GitHub Discussions
        or the community channels are also fine places to ask first.

  - type: dropdown
    id: surface
    attributes:
      label: Surface
      description: Which product surface looks most affected?
      options:
{options}
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the practical impact?
      options:
        - S0 - security risk / data loss
        - S1 - workflow blocked
        - S2 - degraded behavior
        - S3 - minor issue
    validations:
      required: true

  - type: dropdown
    id: regression
    attributes:
      label: Regression?
      options:
        - Unknown
        - Yes, this worked before
        - No, this is a first-time setup or newly exercised path
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: After updating provider profiles, LoongClaw selects the wrong active provider for a channel turn.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
      placeholder: The runtime should preserve the explicitly selected provider profile and route the request through it.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Provide exact commands, config edits, or request flow.
      placeholder: |
        1. Configure provider profile A and provider profile B.
        2. Set profile B as the active profile.
        3. Run `loongclaw ask --message "ping"`.
        4. Observe the request executes through profile A.
      render: bash
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Release tag or exact branch/commit tested.
      placeholder: dev@<commit> or v0.3.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: macOS 15.4 / Ubuntu 24.04 / Windows 11
    validations:
      required: true

  - type: input
    id: runtime_context
    attributes:
      label: Runtime context
      description: Optional but recommended. Include the relevant provider / model / tool / channel / browser / ACP context. Redact secrets.
      placeholder: provider=openrouter, model=claude-sonnet, channel=telegram, tool=browser.open, acp=disabled

  - type: textarea
    id: config_context
    attributes:
      label: Config / environment context
      description: Relevant config keys, env overrides, and feature flags. Redact secrets and private endpoints.
      placeholder: |
        [provider]
        active_profile = "work"

        [tools.browser]
        enabled = true

        Env overrides:
        LOONGCLAW_CONTEXT_ENGINE=legacy

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots / evidence
      description: Paste the shortest logs or screenshots that prove the defect. Redact tokens, credentials, and private data.
      render: text

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who is affected, how often this happens, and what practical damage it causes.
      placeholder: |
        Affected users: contributors testing multi-provider configs
        Frequency: always
        Consequence: wrong provider routing and misleading operator output

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checks
      options:
        - label: I reproduced this on the latest `dev` branch tip or the latest published release.
          required: true
        - label: I redacted secrets, tokens, and private endpoints from everything I attached.
          required: true
        - label: I searched existing issues and did not find the same report already tracked.
          required: true
"""


def render_feature_template(taxonomy: dict) -> str:
    options = render_surface_options(taxonomy)
    return f"""\
{GENERATED_HEADER}name: Feature Request
description: Propose a new capability or meaningful product/runtime improvement.
title: "[Feature]: "
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion.
        Please focus on the user or operator problem, concrete constraints, and what "done" should mean.

  - type: dropdown
    id: surface
    attributes:
      label: Surface
      description: Which product surface would this request primarily affect?
      options:
{options}
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user or system problem are you trying to solve?
      placeholder: Contributors cannot tell which work should land on `dev`, how stable promotions reach `main`, or when a release is expected.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the preferred behavior, UX, API, or workflow.
      placeholder: Add explicit `dev`-branch contribution guidance, narrow `dev -> main` promotion rules, and clearer release-readiness language.
    validations:
      required: true

  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals / out of scope
      description: What should not be included in the first iteration?
      placeholder: Do not add aggressive auto-close bots or a 300-label taxonomy in the first pass.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives did you consider and why not use them?
      placeholder: Keep manual triage, add only docs, or copy OpenClaw's full automation without adaptation.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What concrete outcomes would make this request complete?
      placeholder: |
        - Contributor docs point normal external PRs at `dev`
        - Promotion PRs into `main` stay stabilization-focused
        - Release guidance explains when a stable promotion becomes a tagged release

  - type: dropdown
    id: sensitivity
    attributes:
      label: Policy / security / breaking sensitivity
      options:
        - No, this looks routine
        - Yes, this touches policy, security, or potentially breaking behavior
        - Not sure
    validations:
      required: true

  - type: textarea
    id: rollout
    attributes:
      label: Rollout / rollback notes
      description: Optional. How should this land safely, and how could it be backed out quickly if needed?
      placeholder: Start with documentation + labeler only, then add stronger automation later if triage quality improves.

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits, how often this matters, and what the practical consequence is if it does not land.
      placeholder: |
        Affected users: external contributors and maintainers
        Frequency: every issue / PR intake
        Consequence if missing: more manual triage and weaker review context

  - type: checkboxes
    id: checks
    attributes:
      label: Submission checks
      options:
        - label: I searched existing issues and did not find the same request already tracked.
          required: true
        - label: I used project-scoped wording and removed secrets or private data from examples.
          required: true
"""


def render_docs_template(taxonomy: dict) -> str:
    options = render_surface_options(taxonomy)
    return f"""\
{GENERATED_HEADER}name: Documentation Improvement
description: Report missing, incorrect, or confusing docs and contributor guidance.
title: "[Docs]: "
labels:
  - documentation
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Use this template for documentation drift, missing guidance, broken workflows, confusing
        contributor instructions, or release-process wording that no longer matches reality.

  - type: dropdown
    id: surface
    attributes:
      label: Surface
      description: Which product surface is most affected?
      options:
{options}
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong or missing?
      placeholder: CONTRIBUTING.md still points contributors at `main` even though `dev` is the active integration branch.
    validations:
      required: true

  - type: textarea
    id: current_gap
    attributes:
      label: Current gap
      description: Describe the incorrect, missing, or confusing documentation in detail.
      placeholder: The docs do not explain which branch external contributors should target, and issue intake links do not reflect the current review flow.
    validations:
      required: true

  - type: textarea
    id: proposed_fix
    attributes:
      label: Proposed improvement
      description: What should the documentation say instead?
      placeholder: Add an explicit branch model section, issue intake guidance, and label automation reference.
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence / links
      description: Link the relevant files, PRs, workflows, or screenshots if available.
      placeholder: |
        - CONTRIBUTING.md
        - docs/references/github-collaboration.md
        - .github/ISSUE_TEMPLATE/config.yml
        - .github/workflows/enforce-dev-to-main.yml
        - .github/workflows/release.yml
        - recent PRs targeting dev

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who is confused or blocked, and what practical consequence follows from the current docs?
      placeholder: New contributors follow the wrong branch model and open PRs with the wrong base branch.

  - type: checkboxes
    id: checks
    attributes:
      label: Submission checks
      options:
        - label: I searched existing issues and did not find the same documentation gap already tracked.
          required: true
        - label: I used concrete file or workflow references where possible.
          required: true
"""


def markdown_table(entries: list[dict]) -> str:
    rows = ["| Label | Meaning |", "| --- | --- |"]
    for entry in entries:
        rows.append(f"| `{entry['name']}` | {entry['description']} |")
    return "\n".join(rows)


def render_docs_reference(taxonomy: dict) -> str:
    surface_table = markdown_table(taxonomy["surfaces"])
    domain_table = markdown_table(taxonomy["domains"])
    managed_shared = markdown_table(taxonomy["general_labels"])
    size_table = "\n".join(
        [
            "| Label | Threshold |",
            "| --- | --- |",
            "| `size: XS` | 0-50 changed lines |",
            "| `size: S` | 51-200 changed lines |",
            "| `size: M` | 201-500 changed lines |",
            "| `size: L` | 501-1000 changed lines |",
            "| `size: XL` | More than 1000 changed lines |",
        ]
    )
    return f"""\
{MARKDOWN_GENERATED_HEADER}# GitHub Collaboration Reference

This document defines the active GitHub collaboration baseline for the `dev` branch.

## Active Branch Model

- `dev` is the active integration branch for day-to-day OSS work.
- Contributors should branch from `dev` and target `dev` with normal pull requests.
- `main` is the stable promotion branch. Only reviewed `dev` changes should move into `main`.
- `release` and `release/*` branches are optional release-hardening lanes. When used, they should
  only receive reviewed `main` changes.
- Promotion pull requests into `main` should come from `dev` and stay focused on stabilised work,
  not mixed feature development.

## Promotion and Release Rhythm

- Maintainers aim to promote a stable slice from `dev` into `main` on a regular cadence.
- When a dedicated release-hardening lane is needed, maintainers may promote `main` into `release`
  or `release/*` before tagging.
- Exact timing depends on validation status, scope completion, and operational readiness.
- Releases are published from stable promotion points when the shipped slice is complete enough to
  support a tagged release. Not every `dev -> main` promotion must become a public release.

## CI and Promotion Gates

- `CI`, `CodeQL`, and `Security` validate pull requests and pushes for `dev`, `main`, `release`,
  and `release/*`.
- `perf-lint` uses the same branch set but stays path-scoped to workflow and benchmark-sensitive
  files.
- `enforce-dev-to-main` closes promotion pull requests into `main` when the source is not the
  same-repository `dev` branch.
- `enforce-main-to-release` closes promotion pull requests into `release` lanes when the source is
  not the same-repository `main` branch.
- The stable branch-protection check is `build`, the aggregate job in `.github/workflows/ci.yml`.

## Intake Routes

| Need | Route | Why |
| --- | --- | --- |
| Reproducible runtime defect | Bug report form | Captures severity, regression status, repro, runtime context, and evidence. |
| New capability or behavior change | Feature request form | Captures problem statement, acceptance criteria, rollout notes, and scope boundaries. |
| Missing, wrong, or confusing docs | Documentation improvement form | Captures branch-model drift, workflow gaps, and concrete doc references. |
| Setup question or general troubleshooting | GitHub Discussions, Discord, Telegram, or the community spaces you already use such as Feishu and WeChat | Keeps support traffic out of the issue queue and lets people ask where they already participate. |
| Direct contributor introduction or “where could I help?” conversation | [contact@loongclaw.ai](mailto:contact@loongclaw.ai) | Works well for async introductions, timezone context, and matching contributors to work that fits their strengths. |
| Security vulnerability | Private security advisory | Avoids publishing sensitive details in public issues. |

## Managed Labels

### Surface Labels

These labels route concrete repository surfaces. They intentionally use direct names instead of the
older prefixed taxonomy so the queue reads more like the product and less like a taxonomy dump.

{surface_table}

### Domain Labels

These labels describe broader roadmap slices and cross-cutting themes. They are managed and
documented, but usually applied manually rather than from file paths.

{domain_table}

### Shared Managed Labels

{managed_shared}

### Size Labels

{size_table}

### Existing Default Labels

The collaboration baseline continues to use the platform-default issue-type labels where they fit:

- `bug`
- `enhancement`
- `question`
- `help wanted`
- `good first issue`
- `duplicate`
- `invalid`
- `wontfix`

## Automation Rules

- The `labeler` workflow ensures the managed surface, domain, shared, and `size:*` labels exist.
- Pull requests receive path-based labels from `.github/labeler.yml`.
- Pull requests also receive a single `size:*` label based on total added plus removed lines.
- Pull requests no longer receive a generic `rust` label; the surface labels already carry the
  routing information that matters in this repository.
- Issue forms with a `Surface` dropdown sync to one managed surface label.
- Choosing `Unknown / needs triage` keeps the issue in `triage` without forcing a surface label.
- Maintainers can run `workflow_dispatch` on `labeler` to backfill labels after merging taxonomy
  changes, including legacy prefixed-label migration and `rust` cleanup.

## Pull Request Expectations

- External contributors should normally target `dev`.
- Promotion pull requests into `main` should come from `dev` and stay focused on stabilised work,
  not mixed feature development.
- Link the tracking issue in the PR body and include an explicit closing clause when the PR is meant to resolve it.
- Keep the PR scoped to one logical change stream.
- Fill in the PR template with changed areas, risk track, validation commands, and reviewer focus.
- If the change is Track B, include rollout and rollback notes directly in the PR body.

## Default Branch Notes

GitHub serves public issue forms from the default branch. In this repository, the default branch is
`dev`, which is also the active collaboration baseline. Keep contributor-facing templates, contact
links, and references aligned on `dev` so public intake stays consistent with the actual review
flow.
"""


def target_contents(repo_root: Path, taxonomy: dict) -> dict[Path, str]:
    return {
        repo_root / ".github" / "labeler.yml": render_labeler(taxonomy),
        repo_root / ".github" / "workflows" / "labeler.yml": render_workflow(taxonomy),
        repo_root / ".github" / "ISSUE_TEMPLATE" / "bug_report.yml": render_bug_template(taxonomy),
        repo_root / ".github" / "ISSUE_TEMPLATE" / "feature_request.yml": render_feature_template(taxonomy),
        repo_root / ".github" / "ISSUE_TEMPLATE" / "docs_improvement.yml": render_docs_template(taxonomy),
        repo_root / "docs" / "references" / "github-collaboration.md": render_docs_reference(taxonomy),
    }


def write_targets(targets: dict[Path, str]) -> None:
    for path, content in targets.items():
        path.write_text(content)


def check_targets(targets: dict[Path, str]) -> int:
    mismatches: list[str] = []
    for path, expected in targets.items():
        try:
            actual = path.read_text()
        except FileNotFoundError:
            mismatches.append(f"{path} (missing)")
            continue

        if actual != expected:
            mismatches.append(str(path))

    if mismatches:
        print("GitHub label taxonomy artifacts are out of date:", file=sys.stderr)
        for mismatch in mismatches:
            print(f"  - {mismatch}", file=sys.stderr)
        print("Run `python3 scripts/sync_github_labels.py --write` to refresh them.", file=sys.stderr)
        return 1
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write generated files")
    mode.add_argument("--check", action="store_true", help="verify generated files are up to date")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    taxonomy = load_taxonomy(repo_root)
    targets = target_contents(repo_root, taxonomy)

    if args.check:
        return check_targets(targets)

    write_targets(targets)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
